name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Print environment variable
        run: echo 1 $GITHUB_SHA 2 ${GITHUB_SHA} 3 $SHORT_SHA 4 ${SHORT_SHA}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AMD64
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: GOOS=linux GOARCH=amd64 ARCH=amd64 GIT_SHA=${GITHUB_SHA}
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          no-cache: true
        env:
          GIT_SHA: ${GITHUB_SHA}

      - name: Create new manifest
        run: docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-amd64 ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}